---
version: "2.0"

# Akash Mainnet Example using public providers.

services:  
  redis:
    image: bitnami/redis
    env:
      - REDIS_AOF_ENABLED=no
      # - ALLOW_EMPTY_PASSWORD=yes # testing only
      - REDIS_PASSWORD=rootpassword
    expose:
      - port: 6379        
        to:
          - global: true

  rpc-cache:
    image: reecepbcups/rpc-cache:0.0.7
    depends_on:
      - redis
    env:
      # NOTE - most up to date will be in the docker-compose.yml file
      - REMOTE_CONFIG_TIME_FILE=https://raw.githubusercontent.com/sg-1validator/cosmos-endpoint-cache/main/configs/cache_times.json      
      - REDIS_URL=redis://:rootpassword@akash.provider.domain.here:30830/0      
      - REDIS_RPC_PREFIX=akashrpc
      - ENABLE_COUNTER=false
      - USE_BACKUP_AS_PRIMARY=false
      # Use your own node IPs here as http://
      - RPC_URL=https://rpc-akash.sg-1.online:443
      - BACKUP_RPC_URL=http://bopa7r0l9lflj38paegc137sgo.ingress.europlots.com:80
      - RPC_WEBSOCKET=ws://15.204.143.232:26657/websocket
      - NODE_MONIKER=SG-1
      - RPC_LISTEN_ADDRESS=HIDDEN
      - NODE_TM_VERSION=HIDDEN
      - COINGECKO_ENABLED=true
      # - COINGECKO_API_KEY=HERE
      - COINGECKO_CACHE_SECONDS=6 # do not change if you do not have an API key.
      - COINGECKO_IDS=cosmos,juno-network,osmosis,canto,akash
      - COINGECKO_FIAT=usd,eur,gbp
      - RPC_TITLE=Akash Docker RPC
      - RPC_CUSTOM_TEXT=<a href="https://twitter.com/clydedev_/status/1633511913723240453">Custom caching solution active</a><br><a href="https://api-akash.sg-1.online">SG-1 REST API</a><br>
    expose:
      - port: 5001
        to:
          - global: true       
      - port: 80
        to:
          - global: true 

profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    rpc-cache:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        redis: 
          denom: uakt
          amount: 10000
        rpc-cache: 
          denom: uakt
          amount: 10000

deployment:
  redis:
    akash:
      profile: redis
      count: 1
  rpc-cache:
    akash:
      profile: rpc-cache
      count: 1
